// 100 NEW LISTS TO ADD

  // HEAVY METAL / HARD ROCK (10 lists)
  {
    id: 215,
    title: 'If you like "Mastodon", try these FIVE ALIKE...',
    author: '@metalhead',
    category: 'Music',
    date: '12/10/2024',
    votes: 92,
    upvotes: 95,
    downvotes: 3,
    userVote: null,
    highFives: 48,
    userHighFived: false,
    items: ['Baroness', 'Neurosis', 'Kvelertak', 'High on Fire', 'The Sword'],
    description: 'Progressive sludge metal with complex compositions, heavy riffs, and conceptual depth.',
    comments: [],
    saves: 67,
    isRejected: false
  },
  {
    id: 216,
    title: 'If you like "Iron Maiden", try these FIVE ALIKE...',
    author: '@nwobhm_fan',
    category: 'Music',
    date: '12/10/2024',
    votes: 88,
    upvotes: 92,
    downvotes: 4,
    userVote: null,
    highFives: 45,
    userHighFived: false,
    items: ['Judas Priest', 'Saxon', 'Dio', 'Accept', 'Running Wild'],
    description: 'Classic heavy metal with galloping rhythms, dual guitar harmonies, and epic storytelling.',
    comments: [],
    saves: 61,
    isRejected: false
  },
  {
    id: 217,
    title: 'If you like "Tool", try these FIVE ALIKE...',
    author: '@progmetal',
    category: 'Music',
    date: '12/10/2024',
    votes: 95,
    upvotes: 98,
    downvotes: 3,
    userVote: null,
    highFives: 52,
    userHighFived: false,
    items: ['Porcupine Tree', 'Karnivool', 'Soen', 'Rishloo', 'Ænima-era A Perfect Circle'],
    description: 'Progressive metal with complex time signatures, introspective lyrics, and atmospheric soundscapes.',
    comments: [],
    saves: 71,
    isRejected: false
  },
  {
    id: 218,
    title: 'If you like "Slayer", try these FIVE ALIKE...',
    author: '@thrashmetal',
    category: 'Music',
    date: '12/10/2024',
    votes: 84,
    upvotes: 87,
    downvotes: 3,
    userVote: null,
    highFives: 42,
    userHighFived: false,
    items: ['Testament', 'Exodus', 'Kreator', 'Overkill', 'Dark Angel'],
    description: 'Thrash metal legends with lightning-fast riffs, aggressive vocals, and relentless energy.',
    comments: [],
    saves: 58,
    isRejected: false
  },
  {
    id: 219,
    title: 'If you like "Black Sabbath", try these FIVE ALIKE...',
    author: '@doommetal',
    category: 'Music',
    date: '12/10/2024',
    votes: 102,
    upvotes: 105,
    downvotes: 3,
    userVote: null,
    highFives: 56,
    userHighFived: false,
    items: ['Electric Wizard', 'Sleep', 'Candlemass', 'Saint Vitus', 'Pentagram'],
    description: 'Doom metal pioneers with crushing riffs, dark themes, and heavy, slow tempos.',
    comments: [],
    saves: 76,
    isRejected: false
  },
  {
    id: 220,
    title: 'If you like "Metallica", try these FIVE ALIKE...',
    author: '@classic_thrash',
    category: 'Music',
    date: '12/10/2024',
    votes: 98,
    upvotes: 101,
    downvotes: 3,
    userVote: null,
    highFives: 54,
    userHighFived: false,
    items: ['Megadeth', 'Anthrax', 'Pantera', 'Machine Head', 'Sepultura'],
    description: 'Thrash and groove metal with aggressive riffs, powerful vocals, and anthemic choruses.',
    comments: [],
    saves: 73,
    isRejected: false
  },
  {
    id: 221,
    title: 'If you like "Opeth", try these FIVE ALIKE...',
    author: '@progdeath',
    category: 'Music',
    date: '12/10/2024',
    votes: 89,
    upvotes: 92,
    downvotes: 3,
    userVote: null,
    highFives: 47,
    userHighFived: false,
    items: ['Katatonia', 'Gojira', 'Ne Obliviscaris', 'Edge of Sanity', 'Enslaved'],
    description: 'Progressive death metal with dynamic shifts between heavy and melodic passages.',
    comments: [],
    saves: 64,
    isRejected: false
  },
  {
    id: 222,
    title: 'If you like "System of a Down", try these FIVE ALIKE...',
    author: '@nu_metal',
    category: 'Music',
    date: '12/10/2024',
    votes: 91,
    upvotes: 94,
    downvotes: 3,
    userVote: null,
    highFives: 49,
    userHighFived: false,
    items: ['Deftones', 'Mudvayne', 'Rage Against the Machine', 'Faith No More', 'Mr. Bungle'],
    description: 'Genre-bending metal with unconventional song structures, political themes, and Armenian influences.',
    comments: [],
    saves: 68,
    isRejected: false
  },
  {
    id: 223,
    title: 'If you like "Gojira", try these FIVE ALIKE...',
    author: '@modern_metal',
    category: 'Music',
    date: '12/10/2024',
    votes: 87,
    upvotes: 90,
    downvotes: 3,
    userVote: null,
    highFives: 44,
    userHighFived: false,
    items: ['Meshuggah', 'Lamb of God', 'Mastodon', 'Devin Townsend Project', 'The Ocean'],
    description: 'Technical metal with environmental themes, progressive elements, and crushing heaviness.',
    comments: [],
    saves: 62,
    isRejected: false
  },
  {
    id: 224,
    title: 'If you like "Deftones", try these FIVE ALIKE...',
    author: '@atmospheric_metal',
    category: 'Music',
    date: '12/10/2024',
    votes: 93,
    upvotes: 96,
    downvotes: 3,
    userVote: null,
    highFives: 51,
    userHighFived: false,
    items: ['Loathe', 'Placebo', 'Hum', 'Quicksand', 'Far'],
    description: 'Atmospheric metal with dreamy passages, heavy riffs, and emotional intensity.',
    comments: [],
    saves: 70,
    isRejected: false
  },

  // CAR COMPANIES (8 lists)
  {
    id: 225,
    title: 'If you like "Tesla", try these FIVE ALIKE...',
    author: '@ev_enthusiast',
    category: 'Transportation',
    date: '12/10/2024',
    votes: 112,
    upvotes: 120,
    downvotes: 8,
    userVote: null,
    highFives: 67,
    userHighFived: false,
    items: ['Rivian', 'Lucid Motors', 'Polestar', 'Fisker', 'Nio'],
    description: 'Electric vehicle manufacturers focused on innovation, performance, and sustainability.',
    comments: [],
    saves: 89,
    isRejected: false
  },
  {
    id: 226,
    title: 'If you like "Porsche", try these FIVE ALIKE...',
    author: '@sports_car_lover',
    category: 'Transportation',
    date: '12/10/2024',
    votes: 98,
    upvotes: 103,
    downvotes: 5,
    userVote: null,
    highFives: 58,
    userHighFived: false,
    items: ['Ferrari', 'Lamborghini', 'McLaren', 'Aston Martin', 'Maserati'],
    description: 'Luxury performance car brands with racing heritage and exceptional engineering.',
    comments: [],
    saves: 76,
    isRejected: false
  },
  {
    id: 227,
    title: 'If you like "Toyota", try these FIVE ALIKE...',
    author: '@reliable_rides',
    category: 'Transportation',
    date: '12/10/2024',
    votes: 105,
    upvotes: 110,
    downvotes: 5,
    userVote: null,
    highFives: 63,
    userHighFived: false,
    items: ['Honda', 'Mazda', 'Subaru', 'Hyundai', 'Kia'],
    description: 'Reliable, value-focused automotive brands known for quality and longevity.',
    comments: [],
    saves: 82,
    isRejected: false
  },
  {
    id: 228,
    title: 'If you like "BMW", try these FIVE ALIKE...',
    author: '@german_engineering',
    category: 'Transportation',
    date: '12/10/2024',
    votes: 95,
    upvotes: 100,
    downvotes: 5,
    userVote: null,
    highFives: 56,
    userHighFived: false,
    items: ['Audi', 'Mercedes-Benz', 'Lexus', 'Alfa Romeo', 'Genesis'],
    description: 'Premium automotive brands focused on performance, luxury, and driving dynamics.',
    comments: [],
    saves: 73,
    isRejected: false
  },
  {
    id: 229,
    title: 'If you like "Jeep", try these FIVE ALIKE...',
    author: '@off_road_adventurer',
    category: 'Transportation',
    date: '12/10/2024',
    votes: 102,
    upvotes: 107,
    downvotes: 5,
    userVote: null,
    highFives: 61,
    userHighFived: false,
    items: ['Land Rover', 'Toyota 4Runner', 'Ford Bronco', 'Subaru Outback', 'Rivian R1S'],
    description: 'Rugged off-road vehicles built for adventure and capability.',
    comments: [],
    saves: 79,
    isRejected: false
  },
  {
    id: 230,
    title: 'If you like "Ford Mustang", try these FIVE ALIKE...',
    author: '@muscle_car_fan',
    category: 'Transportation',
    date: '12/10/2024',
    votes: 108,
    upvotes: 113,
    downvotes: 5,
    userVote: null,
    highFives: 65,
    userHighFived: false,
    items: ['Chevrolet Camaro', 'Dodge Challenger', 'Nissan Z', 'Toyota Supra', 'BMW M2'],
    description: 'American muscle and sports cars with powerful engines and aggressive styling.',
    comments: [],
    saves: 85,
    isRejected: false
  },
  {
    id: 231,
    title: 'If you like "Mazda Miata", try these FIVE ALIKE...',
    author: '@roadster_lover',
    category: 'Transportation',
    date: '12/10/2024',
    votes: 94,
    upvotes: 99,
    downvotes: 5,
    userVote: null,
    highFives: 55,
    userHighFived: false,
    items: ['Porsche Boxster', 'Fiat 124 Spider', 'BMW Z4', 'Toyota GR86', 'Honda S2000'],
    description: 'Lightweight roadsters focused on driving enjoyment and handling.',
    comments: [],
    saves: 72,
    isRejected: false
  },
  {
    id: 232,
    title: 'If you like "Rolls-Royce", try these FIVE ALIKE...',
    author: '@ultra_luxury',
    category: 'Transportation',
    date: '12/10/2024',
    votes: 87,
    upvotes: 92,
    downvotes: 5,
    userVote: null,
    highFives: 51,
    userHighFived: false,
    items: ['Bentley', 'Maybach', 'Aston Martin', 'Pagani', 'Bugatti'],
    description: 'Ultra-luxury automotive brands representing the pinnacle of craftsmanship and exclusivity.',
    comments: [],
    saves: 68,
    isRejected: false
  },

  // SNEAKER COMPANIES (6 lists)
  {
    id: 233,
    title: 'If you like "Nike Air Jordan", try these FIVE ALIKE...',
    author: '@sneakerhead',
    category: 'Fashion',
    date: '12/10/2024',
    votes: 118,
    upvotes: 125,
    downvotes: 7,
    userVote: null,
    highFives: 74,
    userHighFived: false,
    items: ['Nike Dunk', 'Adidas Yeezy', 'New Balance 550', 'Reebok Question', 'Converse Weapon'],
    description: 'Basketball-inspired sneakers with street culture appeal and collectible status.',
    comments: [],
    saves: 96,
    isRejected: false
  },
  {
    id: 234,
    title: 'If you like "Adidas Originals", try these FIVE ALIKE...',
    author: '@retro_kicks',
    category: 'Fashion',
    date: '12/10/2024',
    votes: 109,
    upvotes: 115,
    downvotes: 6,
    userVote: null,
    highFives: 68,
    userHighFived: false,
    items: ['Puma Suede', 'Reebok Classic', 'New Balance 990', 'Asics Gel-Lyte', 'Saucony Jazz'],
    description: 'Classic sneaker brands with heritage designs and timeless appeal.',
    comments: [],
    saves: 87,
    isRejected: false
  },
  {
    id: 235,
    title: 'If you like "Vans", try these FIVE ALIKE...',
    author: '@skate_culture',
    category: 'Fashion',
    date: '12/10/2024',
    votes: 112,
    upvotes: 118,
    downvotes: 6,
    userVote: null,
    highFives: 70,
    userHighFived: false,
    items: ['Converse Chuck Taylor', 'DC Shoes', 'Emerica', 'Etnies', 'Nike SB'],
    description: 'Skate-inspired footwear with durable construction and street style.',
    comments: [],
    saves: 90,
    isRejected: false
  },
  {
    id: 236,
    title: 'If you like "On Running", try these FIVE ALIKE...',
    author: '@runner_tech',
    category: 'Fitness',
    date: '12/10/2024',
    votes: 101,
    upvotes: 106,
    downvotes: 5,
    userVote: null,
    highFives: 62,
    userHighFived: false,
    items: ['Hoka One One', 'Brooks', 'Altra', 'Saucony Endorphin', 'New Balance FuelCell'],
    description: 'Performance running shoes with innovative cushioning and technology.',
    comments: [],
    saves: 79,
    isRejected: false
  },
  {
    id: 237,
    title: 'If you like "Common Projects", try these FIVE ALIKE...',
    author: '@minimalist_style',
    category: 'Fashion',
    date: '12/10/2024',
    votes: 96,
    upvotes: 101,
    downvotes: 5,
    userVote: null,
    highFives: 58,
    userHighFived: false,
    items: ['Axel Arigato', 'Koio', 'Greats', 'Oliver Cabell', 'Beckett Simonon'],
    description: 'Minimalist luxury sneakers with clean designs and premium materials.',
    comments: [],
    saves: 75,
    isRejected: false
  },
  {
    id: 238,
    title: 'If you like "Allbirds", try these FIVE ALIKE...',
    author: '@sustainable_fashion',
    category: 'Fashion',
    date: '12/10/2024',
    votes: 104,
    upvotes: 109,
    downvotes: 5,
    userVote: null,
    highFives: 64,
    userHighFived: false,
    items: ['Veja', 'Rothy\'s', 'Cariuma', 'Atoms', 'Thousand Fell'],
    description: 'Sustainable footwear brands using eco-friendly materials and ethical production.',
    comments: [],
    saves: 82,
    isRejected: false
  },

  // MORE MOVIES (12 lists)
  {
    id: 239,
    title: 'If you like "The Matrix", try these FIVE ALIKE...',
    author: '@scifi_cinema',
    category: 'Movies',
    date: '12/10/2024',
    votes: 125,
    upvotes: 132,
    downvotes: 7,
    userVote: null,
    highFives: 81,
    userHighFived: false,
    items: ['Dark City', 'The Thirteenth Floor', 'eXistenZ', 'Ghost in the Shell', 'Blade Runner'],
    description: 'Mind-bending sci-fi films exploring reality, consciousness, and dystopian futures.',
    comments: [],
    saves: 103,
    isRejected: false
  },
  {
    id: 240,
    title: 'If you like "The Grand Budapest Hotel", try these FIVE ALIKE...',
    author: '@wes_anderson_fan',
    category: 'Movies',
    date: '12/10/2024',
    votes: 118,
    upvotes: 124,
    downvotes: 6,
    userVote: null,
    highFives: 75,
    userHighFived: false,
    items: ['The Royal Tenenbaums', 'Moonrise Kingdom', 'Fantastic Mr. Fox', 'The French Dispatch', 'Rushmore'],
    description: 'Whimsical films with meticulous production design, quirky characters, and deadpan humor.',
    comments: [],
    saves: 97,
    isRejected: false
  },
  {
    id: 241,
    title: 'If you like "Parasite", try these FIVE ALIKE...',
    author: '@world_cinema',
    category: 'Movies',
    date: '12/10/2024',
    votes: 132,
    upvotes: 139,
    downvotes: 7,
    userVote: null,
    highFives: 87,
    userHighFived: false,
    items: ['Shoplifters', 'Burning', 'Mother', 'The Handmaiden', 'Memories of Murder'],
    description: 'Korean and Asian cinema exploring class divide, social commentary, and genre-blending.',
    comments: [],
    saves: 109,
    isRejected: false
  },
  {
    id: 242,
    title: 'If you like "Mad Max: Fury Road", try these FIVE ALIKE...',
    author: '@action_junkie',
    category: 'Movies',
    date: '12/10/2024',
    votes: 128,
    upvotes: 135,
    downvotes: 7,
    userVote: null,
    highFives: 84,
    userHighFived: false,
    items: ['The Road Warrior', 'Dredd', 'Snowpiercer', 'John Wick', 'The Raid'],
    description: 'High-octane action films with practical stunts, dystopian settings, and visual spectacle.',
    comments: [],
    saves: 105,
    isRejected: false
  },
  {
    id: 243,
    title: 'If you like "Get Out", try these FIVE ALIKE...',
    author: '@social_horror',
    category: 'Movies',
    date: '12/10/2024',
    votes: 122,
    upvotes: 128,
    downvotes: 6,
    userVote: null,
    highFives: 78,
    userHighFived: false,
    items: ['Us', 'Nope', 'The Invitation', 'Don\'t Breathe', 'A Quiet Place'],
    description: 'Horror films with social commentary, suspenseful storytelling, and psychological depth.',
    comments: [],
    saves: 101,
    isRejected: false
  },
  {
    id: 244,
    title: 'If you like "Blade Runner 2049", try these FIVE ALIKE...',
    author: '@neo_noir',
    category: 'Movies',
    date: '12/10/2024',
    votes: 115,
    upvotes: 121,
    downvotes: 6,
    userVote: null,
    highFives: 72,
    userHighFived: false,
    items: ['Arrival', 'Annihilation', 'Ex Machina', 'Her', 'Under the Skin'],
    description: 'Contemplative sci-fi with stunning visuals, philosophical themes, and atmospheric storytelling.',
    comments: [],
    saves: 94,
    isRejected: false
  },
  {
    id: 245,
    title: 'If you like "Goodfellas", try these FIVE ALIKE...',
    author: '@crime_cinema',
    category: 'Movies',
    date: '12/10/2024',
    votes: 138,
    upvotes: 145,
    downvotes: 7,
    userVote: null,
    highFives: 92,
    userHighFived: false,
    items: ['Casino', 'The Departed', 'Heat', 'Donnie Brasco', 'A Bronx Tale'],
    description: 'Crime dramas with complex characters, moral ambiguity, and Scorsese-style storytelling.',
    comments: [],
    saves: 115,
    isRejected: false
  },
  {
    id: 246,
    title: 'If you like "Whiplash", try these FIVE ALIKE...',
    author: '@intense_drama',
    category: 'Movies',
    date: '12/10/2024',
    votes: 119,
    upvotes: 125,
    downvotes: 6,
    userVote: null,
    highFives: 76,
    userHighFived: false,
    items: ['Black Swan', 'The Wrestler', 'Nightcrawler', 'Birdman', 'Sound of Metal'],
    description: 'Intense character studies about obsession, perfectionism, and the cost of greatness.',
    comments: [],
    saves: 98,
    isRejected: false
  },
  {
    id: 247,
    title: 'If you like "The Big Lebowski", try these FIVE ALIKE...',
    author: '@cult_classics',
    category: 'Movies',
    date: '12/10/2024',
    votes: 126,
    upvotes: 132,
    downvotes: 6,
    userVote: null,
    highFives: 82,
    userHighFived: false,
    items: ['Fargo', 'O Brother, Where Art Thou?', 'Burn After Reading', 'The Nice Guys', 'Kiss Kiss Bang Bang'],
    description: 'Quirky crime comedies with eccentric characters, witty dialogue, and unexpected twists.',
    comments: [],
    saves: 104,
    isRejected: false
  },
  {
    id: 248,
    title: 'If you like "Interstellar", try these FIVE ALIKE...',
    author: '@space_epic',
    category: 'Movies',
    date: '12/10/2024',
    votes: 135,
    upvotes: 142,
    downvotes: 7,
    userVote: null,
    highFives: 89,
    userHighFived: false,
    items: ['The Martian', 'Arrival', 'Gravity', 'Contact', 'Ad Astra'],
    description: 'Epic space exploration films combining scientific concepts with emotional storytelling.',
    comments: [],
    saves: 112,
    isRejected: false
  },
  {
    id: 249,
    title: 'If you like "Eternal Sunshine of the Spotless Mind", try these FIVE ALIKE...',
    author: '@indie_romance',
    category: 'Movies',
    date: '12/10/2024',
    votes: 121,
    upvotes: 127,
    downvotes: 6,
    userVote: null,
    highFives: 77,
    userHighFived: false,
    items: ['Her', '500 Days of Summer', 'Anomalisa', 'The Science of Sleep', 'Synecdoche, New York'],
    description: 'Unconventional romantic films blending surrealism, melancholy, and emotional depth.',
    comments: [],
    saves: 100,
    isRejected: false
  },
  {
    id: 250,
    title: 'If you like "The Shawshank Redemption", try these FIVE ALIKE...',
    author: '@uplifting_drama',
    category: 'Movies',
    date: '12/10/2024',
    votes: 142,
    upvotes: 149,
    downvotes: 7,
    userVote: null,
    highFives: 95,
    userHighFived: false,
    items: ['The Green Mile', 'Stand by Me', 'Forrest Gump', 'The Pursuit of Happyness', 'Dead Poets Society'],
    description: 'Inspirational dramas about hope, friendship, and the human spirit overcoming adversity.',
    comments: [],
    saves: 118,
    isRejected: false
  },

  // MORE PODCASTS (10 lists)
  {
    id: 251,
    title: 'If you like "99% Invisible", try these FIVE ALIKE...',
    author: '@design_podcast',
    category: 'Podcasts',
    date: '12/10/2024',
    votes: 104,
    upvotes: 109,
    downvotes: 5,
    userVote: null,
    highFives: 64,
    userHighFived: false,
    items: ['Twenty Thousand Hertz', 'The Memory Palace', 'Song Exploder', 'Everything is Alive', 'Nice Try!'],
    description: 'Design and storytelling podcasts exploring the hidden world around us.',
    comments: [],
    saves: 82,
    isRejected: false
  },
  {
    id: 252,
    title: 'If you like "How I Built This", try these FIVE ALIKE...',
    author: '@entrepreneur_pod',
    category: 'Podcasts',
    date: '12/10/2024',
    votes: 111,
    upvotes: 117,
    downvotes: 6,
    userVote: null,
    highFives: 69,
    userHighFived: false,
    items: ['Masters of Scale', 'StartUp', 'The Pitch', 'Without Fail', 'Land of the Giants'],
    description: 'Business and entrepreneurship podcasts featuring founder stories and startup journeys.',
    comments: [],
    saves: 88,
    isRejected: false
  },
  {
    id: 253,
    title: 'If you like "Stuff You Should Know", try these FIVE ALIKE...',
    author: '@knowledge_seeker',
    category: 'Podcasts',
    date: '12/10/2024',
    votes: 108,
    upvotes: 114,
    downvotes: 6,
    userVote: null,
    highFives: 67,
    userHighFived: false,
    items: ['No Such Thing As A Fish', 'Ologies', 'Science Vs', 'Underunderstood', 'Every Little Thing'],
    description: 'Educational podcasts making complex topics accessible and entertaining.',
    comments: [],
    saves: 86,
    isRejected: false
  },
  {
    id: 254,
    title: 'If you like "The Daily", try these FIVE ALIKE...',
    author: '@news_junkie',
    category: 'Podcasts',
    date: '12/10/2024',
    votes: 115,
    upvotes: 121,
    downvotes: 6,
    userVote: null,
    highFives: 72,
    userHighFived: false,
    items: ['Up First', 'Today, Explained', 'The Journal', 'Post Reports', 'What Next'],
    description: 'Daily news podcasts providing in-depth analysis of current events.',
    comments: [],
    saves: 91,
    isRejected: false
  },
  {
    id: 255,
    title: 'If you like "Last Podcast on the Left", try these FIVE ALIKE...',
    author: '@true_crime_comedy',
    category: 'Podcasts',
    date: '12/10/2024',
    votes: 102,
    upvotes: 107,
    downvotes: 5,
    userVote: null,
    highFives: 63,
    userHighFived: false,
    items: ['And That\'s Why We Drink', 'Morbid', 'True Crime Garage', 'Small Town Murder', 'Sinisterhood'],
    description: 'True crime podcasts with humor, banter, and entertaining storytelling.',
    comments: [],
    saves: 80,
    isRejected: false
  },
  {
    id: 256,
    title: 'If you like "Hidden Brain", try these FIVE ALIKE...',
    author: '@psychology_pod',
    category: 'Podcasts',
    date: '12/10/2024',
    votes: 106,
    upvotes: 111,
    downvotes: 5,
    userVote: null,
    highFives: 65,
    userHighFived: false,
    items: ['Invisibilia', 'The Happiness Lab', 'You Are Not So Smart', 'All in the Mind', 'The Psychology Podcast'],
    description: 'Psychology and behavioral science podcasts exploring the human mind.',
    comments: [],
    saves: 84,
    isRejected: false
  },
  {
    id: 257,
    title: 'If you like "Pod Save America", try these FIVE ALIKE...',
    author: '@political_pod',
    category: 'Podcasts',
    date: '12/10/2024',
    votes: 98,
    upvotes: 104,
    downvotes: 6,
    userVote: null,
    highFives: 60,
    userHighFived: false,
    items: ['The Ezra Klein Show', 'Strict Scrutiny', 'The Wilderness', 'Lovett or Leave It', 'What a Day'],
    description: 'Progressive political podcasts with analysis, humor, and activism.',
    comments: [],
    saves: 77,
    isRejected: false
  },
  {
    id: 258,
    title: 'If you like "Hardcore History", try these FIVE ALIKE...',
    author: '@history_buff',
    category: 'Podcasts',
    date: '12/10/2024',
    votes: 119,
    upvotes: 125,
    downvotes: 6,
    userVote: null,
    highFives: 75,
    userHighFived: false,
    items: ['Revolutions', 'The History of Rome', 'Fall of Civilizations', 'Tides of History', 'Our Fake History'],
    description: 'Epic historical storytelling with deep dives into pivotal moments and eras.',
    comments: [],
    saves: 95,
    isRejected: false
  },
  {
    id: 259,
    title: 'If you like "The Adventure Zone", try these FIVE ALIKE...',
    author: '@actual_play',
    category: 'Podcasts',
    date: '12/10/2024',
    votes: 101,
    upvotes: 106,
    downvotes: 5,
    userVote: null,
    highFives: 62,
    userHighFived: false,
    items: ['Critical Role', 'Dungeons & Daddies', 'Not Another D&D Podcast', 'Dimension 20', 'The Glass Cannon'],
    description: 'Actual play tabletop RPG podcasts with comedy, storytelling, and improvisation.',
    comments: [],
    saves: 79,
    isRejected: false
  },
  {
    id: 260,
    title: 'If you like "The Michelle Obama Podcast", try these FIVE ALIKE...',
    author: '@inspiring_voices',
    category: 'Podcasts',
    date: '12/10/2024',
    votes: 94,
    upvotes: 99,
    downvotes: 5,
    userVote: null,
    highFives: 57,
    userHighFived: false,
    items: ['We Can Do Hard Things', 'On Being', 'Unlocking Us', 'Super Soul', 'Where Should We Begin?'],
    description: 'Inspirational podcasts featuring thoughtful conversations about life, growth, and humanity.',
    comments: [],
    saves: 74,
    isRejected: false
  },

  // MORE BOOKS (12 lists)
  {
    id: 261,
    title: 'If you like "The Hunger Games", try these FIVE ALIKE...',
    author: '@ya_dystopian',
    category: 'Books',
    date: '12/10/2024',
    votes: 124,
    upvotes: 131,
    downvotes: 7,
    userVote: null,
    highFives: 80,
    userHighFived: false,
    items: ['Divergent', 'The Maze Runner', 'Red Rising', 'The 5th Wave', 'Legend'],
    description: 'Dystopian young adult novels with strong protagonists and rebellion themes.',
    comments: [],
    saves: 102,
    isRejected: false
  },
  {
    id: 262,
    title: 'If you like "The Name of the Wind", try these FIVE ALIKE...',
    author: '@epic_fantasy',
    category: 'Books',
    date: '12/10/2024',
    votes: 131,
    upvotes: 138,
    downvotes: 7,
    userVote: null,
    highFives: 86,
    userHighFived: false,
    items: ['The Way of Kings', 'The Lies of Locke Lamora', 'The Blade Itself', 'Blood Song', 'The Shadow of What Was Lost'],
    description: 'Epic fantasy novels with lyrical prose, magic systems, and complex world-building.',
    comments: [],
    saves: 108,
    isRejected: false
  },
  {
    id: 263,
    title: 'If you like "Educated", try these FIVE ALIKE...',
    author: '@memoir_reader',
    category: 'Books',
    date: '12/10/2024',
    votes: 118,
    upvotes: 124,
    downvotes: 6,
    userVote: null,
    highFives: 74,
    userHighFived: false,
    items: ['The Glass Castle', 'Wild', 'When Breath Becomes Air', 'Know My Name', 'The Year of Magical Thinking'],
    description: 'Powerful memoirs about overcoming hardship, finding identity, and personal transformation.',
    comments: [],
    saves: 96,
    isRejected: false
  },
  {
    id: 264,
    title: 'If you like "The Martian", try these FIVE ALIKE...',
    author: '@hard_scifi',
    category: 'Books',
    date: '12/10/2024',
    votes: 127,
    upvotes: 134,
    downvotes: 7,
    userVote: null,
    highFives: 83,
    userHighFived: false,
    items: ['Project Hail Mary', 'Artemis', 'Seveneves', 'Aurora', 'The Expanse'],
    description: 'Hard science fiction with realistic space exploration, problem-solving, and humor.',
    comments: [],
    saves: 105,
    isRejected: false
  },
  {
    id: 265,
    title: 'If you like "Gone Girl", try these FIVE ALIKE...',
    author: '@psychological_thriller',
    category: 'Books',
    date: '12/10/2024',
    votes: 122,
    upvotes: 128,
    downvotes: 6,
    userVote: null,
    highFives: 78,
    userHighFived: false,
    items: ['The Girl on the Train', 'Sharp Objects', 'The Silent Patient', 'Behind Closed Doors', 'The Woman in the Window'],
    description: 'Psychological thrillers with unreliable narrators and shocking twists.',
    comments: [],
    saves: 100,
    isRejected: false
  },
  {
    id: 266,
    title: 'If you like "The Hobbit", try these FIVE ALIKE...',
    author: '@classic_fantasy',
    category: 'Books',
    date: '12/10/2024',
    votes: 135,
    upvotes: 142,
    downvotes: 7,
    userVote: null,
    highFives: 89,
    userHighFived: false,
    items: ['The Chronicles of Narnia', 'The Princess Bride', 'Stardust', 'The Last Unicorn', 'The Neverending Story'],
    description: 'Whimsical fantasy adventures with charming characters and magical journeys.',
    comments: [],
    saves: 112,
    isRejected: false
  },
  {
    id: 267,
    title: 'If you like "Sapiens", try these FIVE ALIKE...',
    author: '@big_history',
    category: 'Books',
    date: '12/10/2024',
    votes: 129,
    upvotes: 136,
    downvotes: 7,
    userVote: null,
    highFives: 85,
    userHighFived: false,
    items: ['Guns, Germs, and Steel', 'The Dawn of Everything', '21 Lessons for the 21st Century', 'Humankind', 'The Better Angels of Our Nature'],
    description: 'Big history books examining humanity, civilization, and our collective future.',
    comments: [],
    saves: 107,
    isRejected: false
  },
  {
    id: 268,
    title: 'If you like "The Road", try these FIVE ALIKE...',
    author: '@post_apocalyptic',
    category: 'Books',
    date: '12/10/2024',
    votes: 114,
    upvotes: 120,
    downvotes: 6,
    userVote: null,
    highFives: 71,
    userHighFived: false,
    items: ['Station Eleven', 'The Dog Stars', 'The Passage', 'Oryx and Crake', 'Riddley Walker'],
    description: 'Post-apocalyptic novels exploring survival, humanity, and hope amidst devastation.',
    comments: [],
    saves: 93,
    isRejected: false
  },
  {
    id: 269,
    title: 'If you like "The Alchemist", try these FIVE ALIKE...',
    author: '@spiritual_fiction',
    category: 'Books',
    date: '12/10/2024',
    votes: 116,
    upvotes: 122,
    downvotes: 6,
    userVote: null,
    highFives: 73,
    userHighFived: false,
    items: ['Siddhartha', 'The Celestine Prophecy', 'Life of Pi', 'The Little Prince', 'Jonathan Livingston Seagull'],
    description: 'Philosophical fables and spiritual journeys about finding purpose and meaning.',
    comments: [],
    saves: 95,
    isRejected: false
  },
  {
    id: 270,
    title: 'If you like "Big Little Lies", try these FIVE ALIKE...',
    author: '@domestic_drama',
    category: 'Books',
    date: '12/10/2024',
    votes: 119,
    upvotes: 125,
    downvotes: 6,
    userVote: null,
    highFives: 76,
    userHighFived: false,
    items: ['The Husband\'s Secret', 'Little Fires Everywhere', 'The Woman in Cabin 10', 'Then She Was Gone', 'The Perfect Mother'],
    description: 'Domestic thrillers with suburban secrets, complex female characters, and mystery.',
    comments: [],
    saves: 98,
    isRejected: false
  },
  {
    id: 271,
    title: 'If you like "Ready Player One", try these FIVE ALIKE...',
    author: '@geek_culture',
    category: 'Books',
    date: '12/10/2024',
    votes: 121,
    upvotes: 127,
    downvotes: 6,
    userVote: null,
    highFives: 77,
    userHighFived: false,
    items: ['Ender\'s Game', 'Snow Crash', 'Neuromancer', 'Armada', 'Warcross'],
    description: 'Sci-fi adventures blending gaming, virtual reality, and nostalgic pop culture.',
    comments: [],
    saves: 99,
    isRejected: false
  },
  {
    id: 272,
    title: 'If you like "The Handmaid\'s Tale", try these FIVE ALIKE...',
    author: '@feminist_dystopia',
    category: 'Books',
    date: '12/10/2024',
    votes: 126,
    upvotes: 132,
    downvotes: 6,
    userVote: null,
    highFives: 81,
    userHighFived: false,
    items: ['The Testaments', 'The Power', 'Vox', 'Red Clocks', 'The Water Cure'],
    description: 'Feminist dystopian fiction exploring gender, power, and resistance.',
    comments: [],
    saves: 103,
    isRejected: false
  },

  // BURBANK, CA LOCATIONS (14 lists)
  {
    id: 273,
    title: 'Best coffee shops in Burbank, CA',
    author: '@burbank_caffeine',
    category: 'Food',
    date: '12/10/2024',
    votes: 87,
    upvotes: 92,
    downvotes: 5,
    userVote: null,
    highFives: 53,
    userHighFived: false,
    items: ['Romancing the Bean', 'Priscilla\'s Coffee', 'Coffee Commissary', 'Starbucks Reserve', 'Blue Bottle'],
    description: 'Top coffee spots in the Media Capital of the World.',
    comments: [],
    saves: 69,
    isRejected: false
  },
  {
    id: 274,
    title: 'Best restaurants in Burbank, CA',
    author: '@burbank_eats',
    category: 'Food',
    date: '12/10/2024',
    votes: 94,
    upvotes: 99,
    downvotes: 5,
    userVote: null,
    highFives: 58,
    userHighFived: false,
    items: ['Coral Cafe', 'Porto\'s Bakery', 'Granville', 'Tallyrand', 'Bea Bea\'s'],
    description: 'Must-try dining experiences in Burbank.',
    comments: [],
    saves: 75,
    isRejected: false
  },
  {
    id: 275,
    title: 'Best bars in Burbank, CA',
    author: '@burbank_nightlife',
    category: 'Food',
    date: '12/10/2024',
    votes: 82,
    upvotes: 87,
    downvotes: 5,
    userVote: null,
    highFives: 49,
    userHighFived: false,
    items: ['The Castaway', 'Tony\'s Darts Away', 'Basement Tavern', 'Blue Palms', 'Chili John\'s'],
    description: 'Best spots for drinks and nightlife in Burbank.',
    comments: [],
    saves: 65,
    isRejected: false
  },
  {
    id: 276,
    title: 'Best things to do in Burbank, CA',
    author: '@burbank_local',
    category: 'Travel',
    date: '12/10/2024',
    votes: 96,
    upvotes: 101,
    downvotes: 5,
    userVote: null,
    highFives: 59,
    userHighFived: false,
    items: ['Warner Bros. Studio Tour', 'Starlight Bowl', 'Martial Arts History Museum', 'Verdugo Mountains Hiking', 'AMC Burbank 16'],
    description: 'Top attractions and activities in Burbank.',
    comments: [],
    saves: 77,
    isRejected: false
  },
  {
    id: 277,
    title: 'Best pizza in Burbank, CA',
    author: '@burbank_pizza',
    category: 'Food',
    date: '12/10/2024',
    votes: 79,
    upvotes: 84,
    downvotes: 5,
    userVote: null,
    highFives: 47,
    userHighFived: false,
    items: ['Mulberry Street Pizzeria', 'Joe Peep\'s', 'Settebello', 'Lampost Pizza', 'California Pizza Kitchen'],
    description: 'Best pizza joints in Burbank.',
    comments: [],
    saves: 63,
    isRejected: false
  },
  {
    id: 278,
    title: 'Best breakfast in Burbank, CA',
    author: '@burbank_brunch',
    category: 'Food',
    date: '12/10/2024',
    votes: 85,
    upvotes: 90,
    downvotes: 5,
    userVote: null,
    highFives: 51,
    userHighFived: false,
    items: ['The Smokehouse', 'Bea Bea\'s', 'Denny\'s', 'Corner Bakery', 'Jinky\'s Cafe'],
    description: 'Best places for breakfast and brunch in Burbank.',
    comments: [],
    saves: 67,
    isRejected: false
  },
  {
    id: 279,
    title: 'Best shopping in Burbank, CA',
    author: '@burbank_retail',
    category: 'Shopping',
    date: '12/10/2024',
    votes: 76,
    upvotes: 81,
    downvotes: 5,
    userVote: null,
    highFives: 45,
    userHighFived: false,
    items: ['Burbank Town Center', 'IKEA Burbank', 'Costco Burbank', 'Magnolia Park', 'Downtown Burbank'],
    description: 'Top shopping destinations in Burbank.',
    comments: [],
    saves: 61,
    isRejected: false
  },
  {
    id: 280,
    title: 'Best parks in Burbank, CA',
    author: '@burbank_outdoors',
    category: 'Travel',
    date: '12/10/2024',
    votes: 71,
    upvotes: 76,
    downvotes: 5,
    userVote: null,
    highFives: 42,
    userHighFived: false,
    items: ['Stough Canyon Nature Center', 'Johnny Carson Park', 'Olive Recreation Center', 'George Izay Park', 'DeBell Golf Club'],
    description: 'Best outdoor spaces and parks in Burbank.',
    comments: [],
    saves: 57,
    isRejected: false
  },
  {
    id: 281,
    title: 'Best burgers in Burbank, CA',
    author: '@burbank_burgers',
    category: 'Food',
    date: '12/10/2024',
    votes: 83,
    upvotes: 88,
    downvotes: 5,
    userVote: null,
    highFives: 50,
    userHighFived: false,
    items: ['In-N-Out Burger', 'The Counter', 'Five Guys', 'Gordon Biersch', 'Bob\'s Big Boy'],
    description: 'Best burger spots in Burbank.',
    comments: [],
    saves: 66,
    isRejected: false
  },
  {
    id: 282,
    title: 'Best gyms in Burbank, CA',
    author: '@burbank_fitness',
    category: 'Fitness',
    date: '12/10/2024',
    votes: 68,
    upvotes: 73,
    downvotes: 5,
    userVote: null,
    highFives: 40,
    userHighFived: false,
    items: ['LA Fitness', '24 Hour Fitness', 'Burbank Sport Center', 'Orangetheory Fitness', 'Gold\'s Gym'],
    description: 'Top fitness centers and gyms in Burbank.',
    comments: [],
    saves: 54,
    isRejected: false
  },
  {
    id: 283,
    title: 'Best tacos in Burbank, CA',
    author: '@burbank_tacos',
    category: 'Food',
    date: '12/10/2024',
    votes: 81,
    upvotes: 86,
    downvotes: 5,
    userVote: null,
    highFives: 48,
    userHighFived: false,
    items: ['Taqueria Los Cocuyos', 'Chipotle', 'Tacos Don Jorge', 'El Huarachito', 'Taco Bell Cantina'],
    description: 'Best spots for tacos in Burbank.',
    comments: [],
    saves: 64,
    isRejected: false
  },
  {
    id: 284,
    title: 'Best sushi in Burbank, CA',
    author: '@burbank_sushi',
    category: 'Food',
    date: '12/10/2024',
    votes: 77,
    upvotes: 82,
    downvotes: 5,
    userVote: null,
    highFives: 46,
    userHighFived: false,
    items: ['Katsu-Ya', 'Kushiyu', 'Sake House', 'SushiStop', 'Midori Sushi'],
    description: 'Best sushi restaurants in Burbank.',
    comments: [],
    saves: 62,
    isRejected: false
  },
  {
    id: 285,
    title: 'Best bakeries in Burbank, CA',
    author: '@burbank_sweet_tooth',
    category: 'Food',
    date: '12/10/2024',
    votes: 74,
    upvotes: 79,
    downvotes: 5,
    userVote: null,
    highFives: 44,
    userHighFived: false,
    items: ['Porto\'s Bakery', 'Black Cherry Bakery', 'SomiSomi', 'Crumbl Cookies', 'Nothing Bundt Cakes'],
    description: 'Best bakeries and sweet treats in Burbank.',
    comments: [],
    saves: 59,
    isRejected: false
  },
  {
    id: 286,
    title: 'Best live music venues in Burbank, CA',
    author: '@burbank_music',
    category: 'Music',
    date: '12/10/2024',
    votes: 72,
    upvotes: 77,
    downvotes: 5,
    userVote: null,
    highFives: 43,
    userHighFived: false,
    items: ['Starlight Bowl', 'The Castaway', 'Flappers Comedy Club', 'St. Augustine By-The-Sea', 'The Rec Room'],
    description: 'Best venues for live music and performances in Burbank.',
    comments: [],
    saves: 58,
    isRejected: false
  },

  // BOSTON, MA LOCATIONS (18 lists)
  {
    id: 287,
    title: 'Best coffee shops in Boston, MA',
    author: '@boston_coffee',
    category: 'Food',
    date: '12/10/2024',
    votes: 103,
    upvotes: 109,
    downvotes: 6,
    userVote: null,
    highFives: 64,
    userHighFived: false,
    items: ['Thinking Cup', 'Tatte Bakery & Cafe', 'George Howell Coffee', 'Pavement Coffeehouse', 'Barrington Coffee'],
    description: 'Best coffee shops in Beantown.',
    comments: [],
    saves: 82,
    isRejected: false
  },
  {
    id: 288,
    title: 'Best pizza in Boston, MA',
    author: '@boston_pizza',
    category: 'Food',
    date: '12/10/2024',
    votes: 97,
    upvotes: 103,
    downvotes: 6,
    userVote: null,
    highFives: 60,
    userHighFived: false,
    items: ['Regina Pizzeria', 'Santarpio\'s', 'OTTO', 'Picco', 'Area Four'],
    description: 'Best pizza in Boston.',
    comments: [],
    saves: 77,
    isRejected: false
  },
  {
    id: 289,
    title: 'Best seafood in Boston, MA',
    author: '@boston_seafood',
    category: 'Food',
    date: '12/10/2024',
    votes: 108,
    upvotes: 114,
    downvotes: 6,
    userVote: null,
    highFives: 67,
    userHighFived: false,
    items: ['Neptune Oyster', 'Row 34', 'Legal Sea Foods', 'The Barking Crab', 'Island Creek Oyster Bar'],
    description: 'Best seafood restaurants in Boston.',
    comments: [],
    saves: 86,
    isRejected: false
  },
  {
    id: 290,
    title: 'Best bars in Boston, MA',
    author: '@boston_nightlife',
    category: 'Food',
    date: '12/10/2024',
    votes: 94,
    upvotes: 100,
    downvotes: 6,
    userVote: null,
    highFives: 58,
    userHighFived: false,
    items: ['Drink', 'The Hawthorne', 'Yvonne\'s', 'Tunnel', 'The Bell in Hand Tavern'],
    description: 'Best bars and cocktail lounges in Boston.',
    comments: [],
    saves: 75,
    isRejected: false
  },
  {
    id: 291,
    title: 'Best things to do in Boston, MA',
    author: '@boston_tourist',
    category: 'Travel',
    date: '12/10/2024',
    votes: 118,
    upvotes: 125,
    downvotes: 7,
    userVote: null,
    highFives: 74,
    userHighFived: false,
    items: ['Freedom Trail', 'Fenway Park', 'Boston Common', 'Museum of Fine Arts', 'New England Aquarium'],
    description: 'Top attractions and things to do in Boston.',
    comments: [],
    saves: 96,
    isRejected: false
  },
  {
    id: 292,
    title: 'Best Italian food in Boston, MA',
    author: '@boston_italian',
    category: 'Food',
    date: '12/10/2024',
    votes: 101,
    upvotes: 107,
    downvotes: 6,
    userVote: null,
    highFives: 62,
    userHighFived: false,
    items: ['Giacomo\'s', 'Mamma Maria', 'Carmelina\'s', 'The Daily Catch', 'Neptune Oyster'],
    description: 'Best Italian restaurants in Boston, especially in the North End.',
    comments: [],
    saves: 80,
    isRejected: false
  },
  {
    id: 293,
    title: 'Best breakfast in Boston, MA',
    author: '@boston_brunch',
    category: 'Food',
    date: '12/10/2024',
    votes: 92,
    upvotes: 98,
    downvotes: 6,
    userVote: null,
    highFives: 56,
    userHighFived: false,
    items: ['Tatte Bakery', 'The Paramount', 'Mike & Patty\'s', 'South Street Diner', 'The Friendly Toast'],
    description: 'Best breakfast and brunch spots in Boston.',
    comments: [],
    saves: 73,
    isRejected: false
  },
  {
    id: 294,
    title: 'Best parks in Boston, MA',
    author: '@boston_parks',
    category: 'Travel',
    date: '12/10/2024',
    votes: 86,
    upvotes: 92,
    downvotes: 6,
    userVote: null,
    highFives: 52,
    userHighFived: false,
    items: ['Boston Common', 'Public Garden', 'Esplanade', 'Arnold Arboretum', 'Franklin Park'],
    description: 'Best parks and outdoor spaces in Boston.',
    comments: [],
    saves: 68,
    isRejected: false
  },
  {
    id: 295,
    title: 'Best museums in Boston, MA',
    author: '@boston_culture',
    category: 'Art',
    date: '12/10/2024',
    votes: 99,
    upvotes: 105,
    downvotes: 6,
    userVote: null,
    highFives: 61,
    userHighFived: false,
    items: ['Museum of Fine Arts', 'Isabella Stewart Gardner Museum', 'Museum of Science', 'Institute of Contemporary Art', 'Harvard Museums'],
    description: 'Best museums and cultural institutions in Boston.',
    comments: [],
    saves: 79,
    isRejected: false
  },
  {
    id: 296,
    title: 'Best burgers in Boston, MA',
    author: '@boston_burgers',
    category: 'Food',
    date: '12/10/2024',
    votes: 88,
    upvotes: 94,
    downvotes: 6,
    userVote: null,
    highFives: 54,
    userHighFived: false,
    items: ['J.M. Curley', 'Tasty Burger', 'Mr. Bartley\'s', 'Sam\'s', 'Five Guys'],
    description: 'Best burger joints in Boston.',
    comments: [],
    saves: 70,
    isRejected: false
  },
  {
    id: 297,
    title: 'Best shopping in Boston, MA',
    author: '@boston_shopping',
    category: 'Shopping',
    date: '12/10/2024',
    votes: 84,
    upvotes: 90,
    downvotes: 6,
    userVote: null,
    highFives: 51,
    userHighFived: false,
    items: ['Newbury Street', 'Faneuil Hall Marketplace', 'Prudential Center', 'Assembly Row', 'CambridgeSide'],
    description: 'Best shopping destinations in Boston.',
    comments: [],
    saves: 67,
    isRejected: false
  },
  {
    id: 298,
    title: 'Best live music venues in Boston, MA',
    author: '@boston_music',
    category: 'Music',
    date: '12/10/2024',
    votes: 96,
    upvotes: 102,
    downvotes: 6,
    userVote: null,
    highFives: 59,
    userHighFived: false,
    items: ['House of Blues', 'The Paradise Rock Club', 'Brighton Music Hall', 'Royale', 'Paradise Rock Club'],
    description: 'Best live music venues in Boston.',
    comments: [],
    saves: 76,
    isRejected: false
  },
  {
    id: 299,
    title: 'Best tacos in Boston, MA',
    author: '@boston_tacos',
    category: 'Food',
    date: '12/10/2024',
    votes: 82,
    upvotes: 88,
    downvotes: 6,
    userVote: null,
    highFives: 49,
    userHighFived: false,
    items: ['Angela\'s Cafe', 'Tenoch Mexican', 'Loco Taqueria', 'El Jefe\'s Taqueria', 'Lone Star Taco Bar'],
    description: 'Best tacos and Mexican food in Boston.',
    comments: [],
    saves: 65,
    isRejected: false
  },
  {
    id: 300,
    title: 'Best gyms in Boston, MA',
    author: '@boston_fitness',
    category: 'Fitness',
    date: '12/10/2024',
    votes: 76,
    upvotes: 82,
    downvotes: 6,
    userVote: null,
    highFives: 45,
    userHighFived: false,
    items: ['Equinox', 'BSC', 'Orangetheory Fitness', 'CrossFit Boston', 'The Edge Fitness'],
    description: 'Best gyms and fitness centers in Boston.',
    comments: [],
    saves: 61,
    isRejected: false
  },
  {
    id: 301,
    title: 'Best ice cream in Boston, MA',
    author: '@boston_sweet',
    category: 'Food',
    date: '12/10/2024',
    votes: 91,
    upvotes: 97,
    downvotes: 6,
    userVote: null,
    highFives: 56,
    userHighFived: false,
    items: ['Toscanini\'s', 'JP Licks', 'Christina\'s', 'Ben & Jerry\'s', 'Emack & Bolio\'s'],
    description: 'Best ice cream shops in Boston.',
    comments: [],
    saves: 72,
    isRejected: false
  },
  {
    id: 302,
    title: 'Best bakeries in Boston, MA',
    author: '@boston_baked_goods',
    category: 'Food',
    date: '12/10/2024',
    votes: 85,
    upvotes: 91,
    downvotes: 6,
    userVote: null,
    highFives: 52,
    userHighFived: false,
    items: ['Flour Bakery', 'Tatte', 'Mike\'s Pastry', 'Modern Pastry', 'Clear Flour Bread'],
    description: 'Best bakeries and pastry shops in Boston.',
    comments: [],
    saves: 68,
    isRejected: false
  },
  {
    id: 303,
    title: 'Best date night spots in Boston, MA',
    author: '@boston_romance',
    category: 'Romance',
    date: '12/10/2024',
    votes: 93,
    upvotes: 99,
    downvotes: 6,
    userVote: null,
    highFives: 57,
    userHighFived: false,
    items: ['Mistral', 'Menton', 'Ostra', 'No. 9 Park', 'Deuxave'],
    description: 'Best romantic restaurants and date night spots in Boston.',
    comments: [],
    saves: 74,
    isRejected: false
  },
  {
    id: 304,
    title: 'Best rooftop bars in Boston, MA',
    author: '@boston_rooftops',
    category: 'Food',
    date: '12/10/2024',
    votes: 89,
    upvotes: 95,
    downvotes: 6,
    userVote: null,
    highFives: 54,
    userHighFived: false,
    items: ['Lookout Rooftop', 'Citrus & Salt', 'Trophy Room', 'Rooftop at the Envoy', 'The Colonnade Hotel'],
    description: 'Best rooftop bars with views in Boston.',
    comments: [],
    saves: 71,
    isRejected: false
  },

  // ADDITIONAL DIVERSE LISTS (10 lists)
  {
    id: 305,
    title: 'If you like "Stranger Things", try these FIVE ALIKE...',
    author: '@80s_nostalgia',
    category: 'TV Shows',
    date: '12/10/2024',
    votes: 134,
    upvotes: 141,
    downvotes: 7,
    userVote: null,
    highFives: 88,
    userHighFived: false,
    items: ['Dark', 'The Umbrella Academy', 'Locke & Key', 'Archive 81', 'The OA'],
    description: 'Supernatural mysteries with 80s vibes, ensemble casts, and dimensional weirdness.',
    comments: [],
    saves: 111,
    isRejected: false
  },
  {
    id: 306,
    title: 'If you like "The Wire", try these FIVE ALIKE...',
    author: '@prestige_tv',
    category: 'TV Shows',
    date: '12/10/2024',
    votes: 141,
    upvotes: 148,
    downvotes: 7,
    userVote: null,
    highFives: 94,
    userHighFived: false,
    items: ['The Shield', 'Homicide: Life on the Street', 'The Corner', 'We Own This City', 'Treme'],
    description: 'Gritty urban dramas examining institutions, corruption, and social issues.',
    comments: [],
    saves: 117,
    isRejected: false
  },
  {
    id: 307,
    title: 'If you like "Planet Earth", try these FIVE ALIKE...',
    author: '@nature_docs',
    category: 'TV Shows',
    date: '12/10/2024',
    votes: 127,
    upvotes: 134,
    downvotes: 7,
    userVote: null,
    highFives: 83,
    userHighFived: false,
    items: ['Blue Planet', 'Our Planet', 'Life', 'Frozen Planet', 'The Hunt'],
    description: 'Stunning nature documentaries with breathtaking cinematography and David Attenborough.',
    comments: [],
    saves: 105,
    isRejected: false
  },
  {
    id: 308,
    title: 'If you like "Stardew Valley", try these FIVE ALIKE...',
    author: '@cozy_gamer',
    category: 'Games',
    date: '12/10/2024',
    votes: 119,
    upvotes: 126,
    downvotes: 7,
    userVote: null,
    highFives: 76,
    userHighFived: false,
    items: ['Spiritfarer', 'Graveyard Keeper', 'My Time at Portia', 'Littlewood', 'Coral Island'],
    description: 'Cozy farming and life simulation games with charming pixel art and relaxing gameplay.',
    comments: [],
    saves: 98,
    isRejected: false
  },
  {
    id: 309,
    title: 'If you like "Dark Souls", try these FIVE ALIKE...',
    author: '@souls_veteran',
    category: 'Games',
    date: '12/10/2024',
    votes: 126,
    upvotes: 133,
    downvotes: 7,
    userVote: null,
    highFives: 82,
    userHighFived: false,
    items: ['Bloodborne', 'Sekiro', 'Elden Ring', 'Nioh', 'Hollow Knight'],
    description: 'Challenging action RPGs with punishing difficulty, atmospheric worlds, and precise combat.',
    comments: [],
    saves: 104,
    isRejected: false
  },
  {
    id: 310,
    title: 'If you like "The Last of Us", try these FIVE ALIKE...',
    author: '@story_gamer',
    category: 'Games',
    date: '12/10/2024',
    votes: 133,
    upvotes: 140,
    downvotes: 7,
    userVote: null,
    highFives: 87,
    userHighFived: false,
    items: ['A Plague Tale: Innocence', 'The Walking Dead', 'Days Gone', 'Metro Exodus', 'Resident Evil 2'],
    description: 'Post-apocalyptic survival games with emotional storytelling and character-driven narratives.',
    comments: [],
    saves: 110,
    isRejected: false
  },
  {
    id: 311,
    title: 'If you like "The Legend of Zelda: Breath of the Wild", try these FIVE ALIKE...',
    author: '@open_world_explorer',
    category: 'Games',
    date: '12/10/2024',
    votes: 138,
    upvotes: 145,
    downvotes: 7,
    userVote: null,
    highFives: 91,
    userHighFived: false,
    items: ['Genshin Impact', 'Immortals Fenyx Rising', 'Horizon Zero Dawn', 'Ghost of Tsushima', 'Elden Ring'],
    description: 'Open-world adventure games with exploration, discovery, and freedom.',
    comments: [],
    saves: 114,
    isRejected: false
  },
  {
    id: 312,
    title: 'If you like "Catan", try these FIVE ALIKE...',
    author: '@board_game_night',
    category: 'Board Games',
    date: '12/10/2024',
    votes: 102,
    upvotes: 108,
    downvotes: 6,
    userVote: null,
    highFives: 63,
    userHighFived: false,
    items: ['Ticket to Ride', 'Splendor', 'Carcassonne', '7 Wonders', 'Dominion'],
    description: 'Gateway board games with resource management, strategic depth, and player interaction.',
    comments: [],
    saves: 81,
    isRejected: false
  },
  {
    id: 313,
    title: 'If you like "Dungeons & Dragons", try these FIVE ALIKE...',
    author: '@ttrpg_master',
    category: 'Board Games',
    date: '12/10/2024',
    votes: 108,
    upvotes: 114,
    downvotes: 6,
    userVote: null,
    highFives: 67,
    userHighFived: false,
    items: ['Pathfinder', 'Call of Cthulhu', 'Blades in the Dark', 'Fate Core', 'Savage Worlds'],
    description: 'Tabletop RPG systems with rich storytelling, character customization, and collaborative play.',
    comments: [],
    saves: 86,
    isRejected: false
  },
  {
    id: 314,
    title: 'If you like "Gloomhaven", try these FIVE ALIKE...',
    author: '@heavy_gamer',
    category: 'Board Games',
    date: '12/10/2024',
    votes: 95,
    upvotes: 101,
    downvotes: 6,
    userVote: null,
    highFives: 58,
    userHighFived: false,
    items: ['Frosthaven', 'Descent: Legends of the Dark', 'Mage Knight', 'Spirit Island', 'Arkham Horror: The Card Game'],
    description: 'Deep, complex campaign board games with tactical combat and legacy elements.',
    comments: [],
    saves: 76,
    isRejected: false
  },
